# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/redtangle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/redtangle.proto\x12\tredtangle\"\x1c\n\x08Username\x12\x10\n\x08username\x18\x01 \x01(\t\"K\n\nGameStatus\x12\x10\n\x08opponent\x18\x01 \x01(\t\x12\x0c\n\x04turn\x18\x02 \x01(\t\x12\x0e\n\x06winner\x18\x03 \x01(\t\x12\r\n\x05\x62oard\x18\x04 \x01(\t\"2\n\nStatusCode\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.redtangle.StatusCodes\"c\n\x06Status\x12*\n\x0bgame_status\x18\x01 \x01(\x0b\x32\x15.redtangle.GameStatus\x12-\n\rserver_status\x18\x02 \x01(\x0e\x32\x16.redtangle.StatusCodes\"K\n\x12\x43onnectionResponse\x12\x12\n\nteam_color\x18\x01 \x01(\t\x12!\n\x06status\x18\x02 \x01(\x0b\x32\x11.redtangle.Status\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"]\n\rSelectRequest\x12%\n\x08username\x18\x01 \x01(\x0b\x32\x13.redtangle.Username\x12%\n\x08position\x18\x02 \x01(\x0b\x32\x13.redtangle.Position\"R\n\rRotateRequest\x12%\n\x08username\x18\x01 \x01(\x0b\x32\x13.redtangle.Username\x12\x1a\n\x12\x63lockwise_rotation\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty*M\n\x0bStatusCodes\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x0f\n\x0bUSER_EXISTS\x10\x01\x12\r\n\tGAME_FULL\x10\x02\x12\x10\n\x0cSERVER_ERROR\x10\x03\x32\xe6\x02\n\tRedTangle\x12?\n\x07\x43onnect\x12\x13.redtangle.Username\x1a\x1d.redtangle.ConnectionResponse\"\x00\x12\x35\n\tGetStatus\x12\x13.redtangle.Username\x1a\x11.redtangle.Status\"\x00\x12\x37\n\x06Select\x12\x18.redtangle.SelectRequest\x1a\x11.redtangle.Status\"\x00\x12\x37\n\x06Rotate\x12\x18.redtangle.RotateRequest\x1a\x11.redtangle.Status\"\x00\x12\x33\n\x07\x45ndTurn\x12\x13.redtangle.Username\x1a\x11.redtangle.Status\"\x00\x12:\n\nDisconnect\x12\x13.redtangle.Username\x1a\x15.redtangle.StatusCode\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.redtangle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSCODES._serialized_start=595
  _STATUSCODES._serialized_end=672
  _USERNAME._serialized_start=36
  _USERNAME._serialized_end=64
  _GAMESTATUS._serialized_start=66
  _GAMESTATUS._serialized_end=141
  _STATUSCODE._serialized_start=143
  _STATUSCODE._serialized_end=193
  _STATUS._serialized_start=195
  _STATUS._serialized_end=294
  _CONNECTIONRESPONSE._serialized_start=296
  _CONNECTIONRESPONSE._serialized_end=371
  _POSITION._serialized_start=373
  _POSITION._serialized_end=405
  _SELECTREQUEST._serialized_start=407
  _SELECTREQUEST._serialized_end=500
  _ROTATEREQUEST._serialized_start=502
  _ROTATEREQUEST._serialized_end=584
  _EMPTY._serialized_start=586
  _EMPTY._serialized_end=593
  _REDTANGLE._serialized_start=675
  _REDTANGLE._serialized_end=1033
# @@protoc_insertion_point(module_scope)
