import pygame
import math
    
FPS = 60
LEFT_CLICK = 1
RIGHT_CLICK = 3
SCROLL_UP = 4
SCROLL_DOWN = 5
TITLE = 'REDTANGLE'
TOP_RECT = 0
BOTTOM_RECT = 1
RECT_WIDTH = 4
RECT_HEIGHT = 2
GRID_SIZE = 8
EDGE_SIZE = 2
SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SQUARE_WIDTH = SCREEN_WIDTH // GRID_SIZE
SQUARE_HEIGHT = SCREEN_HEIGHT // GRID_SIZE
PIECE_HEIGHT_OFFSET = SQUARE_HEIGHT // 5
PIECE_WIDTH_OFFSET = SQUARE_WIDTH // 5
PIECE_HEIGHT = int(0.85 * SQUARE_HEIGHT) - PIECE_HEIGHT_OFFSET
PIECE_WIDTH = int(0.85 * SQUARE_WIDTH) - PIECE_WIDTH_OFFSET
ORIENTATIONS = 4
RADIUS = int(PIECE_WIDTH * 0.15)
THICKNESS = 2
PHI = math.atan(PIECE_HEIGHT / PIECE_WIDTH)
X_OFFSET = RADIUS * math.cos(PHI)
Y_OFFSET = RADIUS * math.sin(PHI)
RED = pygame.Color(255, 0, 0)
GOLD = pygame.Color(255, int(255 * 0.843), 0) 
BLACK = pygame.Color(0, 0, 0)
WHITE = pygame.Color(255, 255, 255)
