# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debug.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x62ug.proto\x12\x05\x64\x65\x62ug\"\x15\n\x06String\x12\x0b\n\x03str\x18\x01 \x01(\t23\n\x05\x44\x65\x62ug\x12*\n\x08SayHello\x12\r.debug.String\x1a\r.debug.String\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRING._serialized_start=22
  _STRING._serialized_end=43
  _DEBUG._serialized_start=45
  _DEBUG._serialized_end=96
# @@protoc_insertion_point(module_scope)
